name: release windows

on:
  push:
    branch: bin

jobs:
  release:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install . pyinstaller

      - run: pyinstaller bin/_gl2f.py --onefile --name gl2f
      - run: pyinstaller bin/_gl2b.py --onefile --name gl2b
      - run: pyinstaller bin/_gl2r.py --onefile --name gl2r
      - run: pyinstaller bin/_gl2n.py --onefile --name gl2n

      - run: windows.zip dist/*

      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: windows.zip

      - name: Display structure of downloaded files
        run: ls
        run: ls dist